import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import '@/styles/globals.css';
import { Layout } from '@/components/layout/Layout';

type RootLayoutProps = {
  children?: React.ReactNode;
};

const quicksand = Quicksand({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-quicksand',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={quicksand.variable}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
};

export default RootLayout;
